const L={
100:[
["4-3-3","Valdés; Alves, Mascherano, Piqué, Abidal; Busquets, Xavi, Iniesta; Pedro, Messi, Villa","Barcelona, 2011 (Champions League final v Man United)"],
["4-2-3-1","Casillas; Ramos, Piqué, Puyol, Capdevila; Busquets, Xabi Alonso; Pedro, Xavi, Iniesta; Villa","Spain, 2010 (World Cup final v Netherlands)"],
["4-4-2","Van der Sar; Brown, Ferdinand, Vidić, Evra; Hargreaves, Carrick, Scholes, Ronaldo; Rooney, Tevez","Manchester United, 2008 (Champions League final v Chelsea)"],
["4-3-3","Alisson; Alexander-Arnold, Matip, Van Dijk, Robertson; Henderson, Fabinho, Wijnaldum; Salah, Firmino, Mané","Liverpool, 2019 (Champions League final v Tottenham)"],
["4-3-3","E. Martínez; Molina, Romero, Otamendi, Tagliafico; De Paul, Enzo Fernández, Mac Allister; Messi, Álvarez, Di María","Argentina, 2022 (World Cup final v France)"],
["4-2-3-1","Lloris; Pavard, Varane, Umtiti, Hernández; Kanté, Pogba; Mbappé, Griezmann, Matuidi; Giroud","France, 2018 (World Cup final v Croatia)"],
["4-4-2","Lehmann; Lauren, Campbell, Touré, Cole; Ljungberg, Vieira, Gilberto Silva, Pires; Bergkamp, Henry","Arsenal, 2003–04 (the Invincibles)"],
["4-2-3-1","Neuer; Lahm, Boateng, Hummels, Höwedes; Schweinsteiger, Kramer; Müller, Kroos, Özil; Klose","Germany, 2014 (World Cup final v Argentina)"],
["3-2-4-1","Ederson; Stones, Dias, Aké; Walker, Rodri; Bernardo Silva, De Bruyne, Gündoğan, Grealish; Haaland","Manchester City, 2023 (Champions League final v Inter)"],
["4-3-1-2","Navas; Carvajal, Varane, Ramos, Marcelo; Casemiro, Modrić, Kroos; Isco; Benzema, Ronaldo","Real Madrid, 2017 (Champions League final v Juventus)"],
["4-3-3","ter Stegen; Alves, Piqué, Mascherano, Alba; Rakitić, Busquets, Iniesta; Messi, Suárez, Neymar","Barcelona, 2015 (Champions League final v Juventus)"],
["4-3-3","Donnarumma; Hakimi, Marquinhos, Pacho, Nuno Mendes; Neves, Vitinha, Fabián Ruiz; Doué, Dembélé, Kvaratskhelia","Paris Saint-Germain, 2025 (Champions League final v Inter)"],
],
200:[
["4-2-3-1","Čech; Bosingwa, Cahill, David Luiz, Cole; Mikel, Lampard; Kalou, Mata, Bertrand; Drogba","Chelsea, 2012 (Champions League final v Bayern)"],
["4-4-1-1","Dudek; Finnan, Carragher, Hyypiä, Traoré; Luis García, Gerrard, Xabi Alonso, Riise; Kewell; Baroš","Liverpool, 2005 (Champions League final v AC Milan, Istanbul)"],
["4-2-3-1","Júlio César; Maicon, Lúcio, Samuel, Chivu; Zanetti, Cambiasso; Eto'o, Sneijder, Pandev; Milito","Inter, 2010 (Champions League final v Bayern)"],
["4-4-2","Schmeichel; Simpson, Morgan, Huth, Fuchs; Mahrez, Kanté, Drinkwater, Albrighton; Okazaki, Vardy","Leicester City, 2015–16 (the title season)"],
["4-2-3-1","Neuer; Lahm, Boateng, Dante, Alaba; Javi Martínez, Schweinsteiger; Robben, Müller, Ribéry; Mandžukić","Bayern Munich, 2013 (Champions League final v Dortmund)"],
["4-3-3","Casillas; Carvajal, Varane, Ramos, Coentrão; Khedira, Modrić, Di María; Bale, Benzema, Ronaldo","Real Madrid, 2014 (Champions League final v Atlético, La Décima)"],
["3-4-2-1","Marcos; Lúcio, Edmílson, Roque Júnior; Cafu, Gilberto Silva, Kléberson, Roberto Carlos; Ronaldinho, Rivaldo; Ronaldo","Brazil, 2002 (World Cup final v Germany)"],
["4-2-3-1","Buffon; Zambrotta, Cannavaro, Materazzi, Grosso; Gattuso, Pirlo; Camoranesi, Perrotta, Totti; Toni","Italy, 2006 (World Cup final v France)"],
["3-4-2-1","Mendy; Azpilicueta, Thiago Silva, Rüdiger; James, Kanté, Jorginho, Chilwell; Mount, Havertz; Werner","Chelsea, 2021 (Champions League final v Man City)"],
["4-2-3-1","Unai Simón; Carvajal, Le Normand, Laporte, Cucurella; Rodri, Fabián Ruiz; Yamal, Olmo, Nico Williams; Morata","Spain, 2024 (Euro final v England)"],
["4-3-3","Valdés; Puyol, Touré, Piqué, Sylvinho; Busquets, Xavi, Iniesta; Eto'o, Messi, Henry","Barcelona, 2009 (Champions League final v Man United)"],
["4-3-3","Courtois; Carvajal, Militão, Alaba, Mendy; Modrić, Casemiro, Kroos; Valverde, Benzema, Vinícius","Real Madrid, 2022 (Champions League final v Liverpool)"],
],
300:[
["4-4-2","Schmeichel; G. Neville, Johnsen, Stam, Irwin; Beckham, Butt, Giggs, Blomqvist; Cole, Yorke","Manchester United, 1999 (Champions League final v Bayern)"],
["4-3-2-1","Dida; Oddo, Nesta, Maldini, Jankulovski; Gattuso, Pirlo, Ambrosini; Seedorf, Kaká; Inzaghi","AC Milan, 2007 (Champions League final v Liverpool)"],
["4-2-3-1","Lloris; Trippier, Alderweireld, Vertonghen, Rose; Sissoko, Winks; Eriksen, Alli, Son; Kane","Tottenham, 2019 (Champions League final v Liverpool)"],
["4-1-3-2","Rui Patrício; Cédric, Pepe, Fonte, Guerreiro; William Carvalho; Renato Sanches, Adrien Silva, João Mário; Nani, Ronaldo","Portugal, 2016 (Euro final v France)"],
["4-2-3-1","Neuer; Kimmich, Boateng, Alaba, Davies; Thiago, Goretzka; Gnabry, Müller, Coman; Lewandowski","Bayern Munich, 2020 (Champions League final v PSG)"],
["4-4-2","Hart; Zabaleta, Kompany, Lescott, Clichy; Silva, Barry, Yaya Touré, Nasri; Tevez, Agüero","Manchester City, 2012 (title decider v QPR, the 93:20 game)"],
["4-3-3","Čech; Essien, Carvalho, Terry, A. Cole; Ballack, Makélélé, Lampard; J. Cole, Drogba, Malouda","Chelsea, 2008 (Champions League final v Man United)"],
["4-6-0","Casillas; Arbeloa, Piqué, Ramos, Alba; Busquets, Xabi Alonso; Silva, Xavi, Iniesta, Fàbregas","Spain, 2012 (Euro final v Italy)"],
["4-4-2","Courtois; Juanfran, Miranda, Godín, Filipe Luís; Raúl García, Gabi, Tiago, Koke; Villa, Diego Costa","Atlético Madrid, 2014 (Champions League final v Real Madrid)"],
["4-3-3","Karius; Alexander-Arnold, Lovren, Van Dijk, Robertson; Henderson, Milner, Wijnaldum; Salah, Firmino, Mané","Liverpool, 2018 (Champions League final v Real Madrid)"],
["4-4-2","Courtois; Carvajal, Rüdiger, Nacho, Mendy; Valverde, Camavinga, Kroos, Bellingham; Vinícius, Rodrygo","Real Madrid, 2024 (Champions League final v Dortmund)"],
["4-3-3","Meret; Di Lorenzo, Rrahmani, Kim Min-jae, Mário Rui; Anguissa, Lobotka, Zieliński; Politano, Osimhen, Kvaratskhelia","Napoli, 2022–23 (the Scudetto season)"],
],
400:[
["4-3-1-2","Vítor Baía; Paulo Ferreira, Jorge Costa, Ricardo Carvalho, Nuno Valente; Costinha, Maniche, Pedro Mendes; Deco; Derlei, Carlos Alberto","Porto, 2004 (Champions League final v Monaco)"],
["4-3-3","Nikopolidis; Seitaridis, Dellas, Kapsis, Fyssas; Zagorakis, Katsouranis, Basinas; Giannakopoulos, Charisteas, Vryzas","Greece, 2004 (Euro final v Portugal)"],
["4-5-1","Lehmann; Eboué, Touré, Campbell, Cole; Hleb, Gilberto Silva, Fàbregas, Ljungberg, Pires; Henry","Arsenal, 2006 (Champions League final v Barcelona)"],
["4-2-3-1","Weidenfeller; Piszczek, Subotić, Hummels, Schmelzer; Bender, Gündoğan; Błaszczykowski, Reus, Großkreutz; Lewandowski","Borussia Dortmund, 2013 (Champions League final v Bayern)"],
["4-2-3-1","Stekelenburg; Van der Wiel, Heitinga, Mathijsen, Van Bronckhorst; Van Bommel, De Jong; Robben, Sneijder, Kuyt; Van Persie","Netherlands, 2010 (World Cup final v Spain)"],
["4-2-3-1","Subašić; Vrsaljko, Lovren, Vida, Strinić; Brozović, Rakitić; Rebić, Modrić, Perišić; Mandžukić","Croatia, 2018 (World Cup final v France)"],
["4-4-2","César; Míchel Salgado, Hierro, Helguera, Roberto Carlos; Figo, Makélélé, Solari, Zidane; Raúl, Morientes","Real Madrid, 2002 (Champions League final v Leverkusen, Zidane's volley)"],
["3-5-2","Kahn; Linke, Ramelow, Metzelder; Frings, Schneider, Hamann, Jeremies, Bode; Klose, Neuville","Germany, 2002 (World Cup final v Brazil)"],
["3-5-2","Onana; Darmian, Acerbi, Bastoni; Dumfries, Barella, Brozović, Çalhanoğlu, Dimarco; Džeko, Lautaro","Inter, 2023 (Champions League final v Man City)"],
["4-3-3","E. Martínez; Montiel, Romero, Otamendi, Acuña; De Paul, Paredes, Lo Celso; Di María, Lautaro, Messi","Argentina, 2021 (Copa América final v Brazil)"],
["4-3-3","Kepa; Azpilicueta, Christensen, David Luiz, Emerson; Kanté, Jorginho, Kovačić; Pedro, Giroud, Hazard","Chelsea, 2019 (Europa League final v Arsenal)"],
["4-4-2","Van der Sar; O'Shea, Ferdinand, Vidić, Evra; Park, Anderson, Carrick, Giggs; Ronaldo, Rooney","Manchester United, 2009 (Champions League final v Barcelona)"],
],
500:[
["3-4-2-1","Hrádecký; Tapsoba, Tah, Hincapié; Frimpong, Andrich, Xhaka, Grimaldo; Hofmann, Wirtz; Boniface","Bayer Leverkusen, 2023–24 (the unbeaten Bundesliga season)"],
["4-4-2","Halldórsson; Sævarsson, R. Sigurðsson, Árnason, Skúlason; Guðmundsson, Gunnarsson, G. Sigurðsson, B. Bjarnason; Sigþórsson, Böðvarsson","Iceland, 2016 (beat England at the Euros)"],
["4-1-4-1","Bounou; Hakimi, Dari, Saïss, Attiyat Allah; Amrabat; Ziyech, Ounahi, Amallah, Boufal; En-Nesyri","Morocco, 2022 (World Cup quarter-final v Portugal)"],
["3-4-1-2","Musso; Djimsiti, Hien, Kolašinac; Zappacosta, De Roon, Éderson, Ruggeri; Koopmeiners; De Ketelaere, Lookman","Atalanta, 2024 (Europa League final v Leverkusen)"],
["4-3-3","Al-Owais; Abdulhamid, Al-Amri, Al-Bulayhi, Al-Shahrani; Kanno, Al-Malki, Al-Faraj; Al-Buraikan, Al-Shehri, Al-Dawsari","Saudi Arabia, 2022 (beat Argentina at the World Cup)"],
["4-2-3-1","El-Shenawy; Ahmed Fathy, Gabr, Hegazi, Abdel-Shafy; Tarek Hamed, Elneny; Trezeguet, Abdallah Said, Warda; Marwan Mohsen","Egypt, 2018 (World Cup v Uruguay, Salah on the bench)"],
["4-2-3-1","Onana; Mazraoui, De Ligt, Blind, Tagliafico; Schöne, De Jong; Ziyech, Van de Beek, Neres; Tadić","Ajax, 2019 (Champions League semi-final v Tottenham)"],
["3-4-2-1","Trapp; Tuta, Hinteregger, N'Dicka; Knauff, Sow, Rode, Kostić; Lindstrøm, Kamada; Borré","Eintracht Frankfurt, 2022 (Europa League final v Rangers)"],
["4-3-3","Ederson; Walker, Stones, Dias, Zinchenko; Gündoğan, Bernardo Silva, Foden; Mahrez, De Bruyne, Sterling","Manchester City, 2021 (Champions League final v Chelsea, no striker)"],
["4-3-3","Romero; Valencia, Smalling, Blind, Darmian; Herrera, Pogba, Fellaini; Mata, Mkhitaryan, Rashford","Manchester United, 2017 (Europa League final v Ajax)"],
["4-2-3-1","Kobel; Ryerson, Hummels, Schlotterbeck, Maatsen; Can, Sabitzer; Sancho, Brandt, Adeyemi; Füllkrug","Borussia Dortmund, 2024 (Champions League final v Real Madrid)"],
["4-3-3","Valdés; Oleguer, Puyol, Márquez, Van Bronckhorst; Edmílson, Van Bommel, Deco; Giuly, Eto'o, Ronaldinho","Barcelona, 2006 (Champions League final v Arsenal)"],
]};
const data={};
for(const v in L) data[v]=L[v].map(([f,s,a])=>{const rows=s.split(';').map(r=>r.split(',').map(x=>x.trim()));
  const n=rows.reduce((t,r)=>t+r.length,0); if(n!==11) throw new Error(a+' has '+n);
  return [f+"\n"+rows.slice().reverse().map(r=>r.join(' · ')).join("\n"),a];});
require('fs').writeFileSync('/mnt/project-files/jeopardy/v4work/out/form.json',JSON.stringify({id:"form",name:"Formations",type:"text",desc:"A full starting lineup, strikers at the top and the keeper at the bottom. Name the team and the year.",data},null,1));
console.log(Object.values(data).map(a=>a.length));
